{"name": "Логин c некорректными данными", "status": "passed", "description": "Проверяем, что запрос на логин с некорректными данными вернет код 403 и ошибкой в теле ответа", "steps": [{"name": "Логинимся юзером", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'ccbfxcbdvr@mail.ru', 'password': 'dxyhondhld', 'name': 'vujogqusix'}"}], "start": 1724363627901, "stop": 1724363628348}], "start": 1724363627901, "stop": 1724363628349, "uuid": "b87723ea-0083-440b-b38c-b2436e420c9f", "historyId": "3b7cc68bf2e4034364ffb17032b8f151", "testCaseId": "3b7cc68bf2e4034364ffb17032b8f151", "fullName": "tests.test_user_login.TestUserLogin#test_user_login_wrong_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "i111435269"}, {"name": "thread", "value": "76322-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}